### ISSUE TITLE
License of the project

### ISSUE THREAD

**Issue by Ashvith10** [mintRaven-05/Toralizer#1]
The author has mentioned that they're not okay with sharing the source code, as it is the only way to monetize their content. I doubt if you can upload this, let alone decide on your own license for a project that belongs to someone else.

In the `README.md` file, you've mentioned:

>Copyright © 2024 [Debjeet Banerjee](https://github.com/mintRaven-05)

**Comment by mintRaven-05** [comment]
This project is a modified version of the original version created by Jonas Birch. It currently supports ssh and curl without SSL with some minor tweaks in the output and thus the copyright under my name. However, I do understand your concern and can surely mention him in `README.md`.
